name: denemeye_devam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # SDK aralığını belirtmek daha güvenlidir.

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  uuid: ^4.5.1
  supabase_flutter: ^2.9.1
  provider: ^6.1.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Varlıklarınızı (assets) buraya ekleyin.
  # Yeni tasarım için logo klasörünü ekledim.
  assets:
    - .env
    - assets/images/ # Logo ve diğer görseller için
    - assets/map_placeholder.png
    - assets/logos/

  # Fontlarınızı buraya ekleyin.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700